name: StackQueueBuild

on:
  push

jobs:
  windows-build:
    runs-on: windows-2019
    steps:
        - uses: actions/checkout@v2
        - run: |
            mkdir build
            cmake -Bbuild -G "Visual Studio 16 2019"       
            cmake --build build
            .\build\bin\test_stack_and_queue.exe
    
  linux-build:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2
        - run: |
            mkdir build
            cmake -Bbuild -G "Unix Makefiles"       
            cmake --build build
            ./build/bin/test_stack_and_queue
